# Generated by Django 3.2.5 on 2021-07-26 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bolsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=70)),
                ('fecha', models.CharField(max_length=70)),
                ('hora', models.IntegerField()),
                ('minuto', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('opeN', models.DecimalField(decimal_places=4, max_digits=10)),
                ('high', models.DecimalField(decimal_places=4, max_digits=10)),
                ('loW', models.DecimalField(decimal_places=4, max_digits=10)),
                ('close', models.DecimalField(decimal_places=4, max_digits=10)),
                ('volume', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bolsa1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=70)),
                ('fecha', models.CharField(max_length=70)),
                ('hora', models.IntegerField()),
                ('minuto', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('opeN', models.DecimalField(decimal_places=4, max_digits=10)),
                ('high', models.DecimalField(decimal_places=4, max_digits=10)),
                ('loW', models.DecimalField(decimal_places=4, max_digits=10)),
                ('close', models.DecimalField(decimal_places=4, max_digits=10)),
                ('volume', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechasymbol', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Html',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.TextField(blank=True)),
            ],
        ),
    ]
